### ISSUE TITLE
when an error is thrown, any way to also get the error code vs just the error message?

### ISSUE THREAD

**Issue by lcanali** [DigitalOceanPHP/DigitalOceanV2#157]
The DO folks said that processing or error code versus error message should be the way to go.

thanks!

**Comment by glennjacobs** [comment]
Marked as an enhancement to see if it needs looking at.

**Comment by GrahamCampbell** [comment]
Moving to part of the v4 design issue https://github.com/DigitalOceanPHP/DigitalOceanV2/issues/249. I am planning to smash out a fresh package for v4 which will feel like the old package, but have none of the issues and all of the compatibility. ;)
