### ISSUE TITLE
Expand Core Team / Move to GitHub Organization

### ISSUE THREAD

**Issue by Teevio** [DigitalOceanPHP/DigitalOceanV2#163]
Hey @toin0u @GrahamCampbell @yassirh (not sure who to tag here), DigitalOcean has been making many strides in their API, with lots more in the works.  This Github repo is invaluable to the PHP community and those who are using Laravel, but it seems like nothing is happening in regard to pull requests and enhancements.

If there is no interest in continuing the maintenance of this repo, it'd be awesome to hand it off to someone who has the time and is interested in it's continued development.  I know I'd be super interested in managing it and making sure things are moving forward.  I'm sure there are plenty of others who would be too.

**Comment by GrahamCampbell** [comment]
This repo remains maintained, but as with all community projects, we appreciate community PRs to add new things.

**Comment by GrahamCampbell** [comment]
Looks like the current PRs are not ready to be merged yet.

**Comment by Teevio** [comment]
Thanks, but there has been zero responses to the PRs, so I think people who are making changes, just don't know what's going on.

**Comment by GrahamCampbell** [comment]
Yeh, that's fair. I have no objections to you coming on board as a collaborator, though I guess it's not really totally up-to-me.

TBH, I'd quite like to see this repo moved to an organization, where it can get some proper love from a small core team.

// cc @toin0u

**Comment by GrahamCampbell** [comment]
I've updated the issue title to reflect what I think should probably happen here. :)

**Comment by Teevio** [comment]
Awesome 👍 I'll try and help out with stuffs around here too.  DO is going to be adding in API support for all of their monitoring features so it's going to be a little more busy around here.

**Comment by yassirh** [comment]
Hello everyone, I have not been able to review/merge any PRs recently. As @GrahamCampbell have mentioned this library is still maintained.

As for expanding the core team, I think that it is a good idea 👍

**Comment by GrahamCampbell** [comment]
Since this repo does not belong to an organization, we need @toin0u to personally add @Teevio as a collaborator, or to move this repo to an organization.

**Comment by scp** [comment]
Any update on this? Shame to see the library get stale as the API advances. 

I'm sure there are plenty in the community who would see it's kept up to date if they were given access.

Otherwise perhaps it's a good idea to fork to ensure development continues @Teevio ?

**Comment by Teevio** [comment]
@scp I was never added (which is fine since I haven't been doing much PHP anymore), but I'd definitely suggest forking this and actively developing elsewhere.

**Comment by GrahamCampbell** [comment]
See https://github.com/toin0u/DigitalOceanV2/issues/237. I have now left as a maintainer of this repo.
