### ISSUE TITLE
Help with the API - having some problems.

### ISSUE THREAD

**Issue by eddiejibson** [DigitalOceanPHP/DigitalOceanV2#180]
Hi @toin0u,

So I'm relatively new to PHP, and especially the Digital Ocean API for PHP that has been nicely created. I've created this issue in hope of solving the problems I was having trying to implement it into the project I've been working on. Any help regarding the matter would be greatly appreciated. 

Anyway, so basically, I was trying to fetch information about a specific domain and tried to return information via an Array. It wasn't working, so I referred to the documentation in hopes of this solving my issue. It was mentioned that the output for such a function would be "\DigitalOceanV2\Entity\Domain" I didn't quite understand this at first, as when I used a json_decode function, it seemed to output an array. I even tried the build() function that was mentioned, too. Again,that didn't work as I had hoped. I suppose the question is how can I output it via echo, and how could I display only a segment of such data (say only the name or records?). I had the same issues with echoing out all existing DNS records within a certain domain. An example would be most helpful.

Thank-you in advance.

**Comment by Teevio** [comment]
Hi there @eddiejibson the response that this library returns is an object, not an array.  For example if you wanted to get all the non attached floating IPs you might do something like this:

		$FloatingIps = DigitalOcean::floatingIp()->getAll();
		$ips = [];

		foreach ($FloatingIps as $FloatingIp) {
			if (is_null($FloatingIp->droplet)) {
				$ips[] = [
					'ip' => $FloatingIp->ip
				];
			}
		}

**Comment by eddiejibson** [comment]
Great, @Teevio, thank-you very much.

I assume I can echo out various information about domains within that loop too?

**Comment by Teevio** [comment]
Yes, you should reference the DO API docs to see what DO is going to be returning in a specific response.
