### ISSUE TITLE
Question regarding the proper way to create a droplet with ssh_keys

### ISSUE THREAD

**Issue by ppcheng** [DigitalOceanPHP/DigitalOceanV2#181]
According to Digital Ocean docs, if we successfully create a droplet with ssh_keys, then their system will not send any root password emails. However, when I was using the creation api with $sshKeys specified, I still receive the root password email every time a droplet is created successfully. What is the proper to create a droplet with ssh keys without any need of root password email?

**Comment by ppcheng** [comment]
This is the code I was using:
```
$created = $droplet->create('scaffolding-' . mt_rand(), 'tor1', '512mb', $image=$imageId, $sshKeys=array($keyId));
```

**Comment by krisnaw** [comment]
Same issue. I've tried using, ID, Name, and fingerpring. But its keep getting email.
 For example `$sshKeys = ['1232435']`

**Comment by daniel-farina** [comment]
Thank you I was about to post the same reply. 

I got it to work as you said by doing:
```
 $created = $droplet->create('test01', 'nyc1', '512mb','ubuntu-14-04-x64','','','',['22045720']);
```

**Comment by krisnaw** [comment]
I think we can close this case
