### ISSUE TITLE
ip addresses aren't always returned

### ISSUE THREAD

**Issue by lcanali** [DigitalOceanPHP/DigitalOceanV2#188]
I implemented your suggestion to retrieve the ip addresses as suggested here: https://github.com/toin0u/DigitalOceanV2/issues/76

$ips = array_map(function ($network) {
    if ('public' === $network->type) {
        return $network->ipAddress;
    }
}, $userAtom->networks);
echo $ips[0];

but I'm still getting instances where I simply keep polling  for the ips to show up and they never do.  Meanwhile I can see that the droplet does have an ipv4 and an ipv6 ip assigned to it.

We've noticed that this behavior started recently in the past 2-3 weeks, so something may have changed on the DO side.

Could you please give it a try on a few droplets.  We have luck reproducing this in San Fran and Amsterdam data centers.

thanks

**Comment by glennjacobs** [comment]
I've not seen this and considering this was back in 2017, I'll close.
