### ISSUE TITLE
Fatal error when handling error

### ISSUE THREAD

**Issue by bravadomizzou** [DigitalOceanPHP/DigitalOceanV2#190]
Fatal error: Call to a member function getBody() on a non-object in /vendor/toin0u/digitalocean-v2/src/Adapter/GuzzleHttpAdapter.php on line 133

line in question: `$body = (string) $this->response->getBody();`

I get this error almost weekly (usually a direct result of Digital Ocean experiencing networking problems) and it breaks a cronjob, the issue seems to be that sometimes there is no response, can someone make a new exception for when there is no response

**Comment by glennjacobs** [comment]
See #229 for more recent report of this bug.
