### ISSUE TITLE
API request: Create droplets from snapshots

### ISSUE THREAD

**Issue by hailite** [DigitalOceanPHP/DigitalOceanV2#198]
Currently snapshots APIs only have List/Delete. Can we have one to create new droplets from a snapshot? Thanks

**Comment by yokowasis** [comment]
+1 for this. We need more snapshot operation.

**Comment by GrahamCampbell** [comment]
#238,

**Comment by GrahamCampbell** [comment]
Moving to part of the v4 design issue #249. I am planning to smash out a fresh package for v4 which will feel like the old package, but have none of the issues and all of the compatibility. ;)

**Comment by GrahamCampbell** [comment]
This already exists. Pass the snapshot ID as the image parameter when creating a droplet.
