### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Wrong parameters for DigitalOceanV2\Exception\HttpException([string $message [, long $code [, Throwable $previous = NULL]]])

### ISSUE THREAD

**Issue by iqdoctor** [DigitalOceanPHP/DigitalOceanV2#201]
PHP Fatal error:  Uncaught Error: Wrong parameters for DigitalOceanV2\Exception\HttpException([string $message [, long $code [, Throwable $previous = NULL]]]) in /home/iqdoctor/Hr360Bot/vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php:148
Stack trace:
#0 /home/iqdoctor/Hr360Bot/vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php(148): Exception->__construct(Object(stdClass), 422)
#1 /home/iqdoctor/Hr360Bot/vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php(133): DigitalOceanV2\Adapter\BuzzAdapter->handleError(Object(Buzz\Message\Response))
#2 /home/iqdoctor/Hr360Bot/vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php(65): DigitalOceanV2\Adapter\BuzzAdapter->handleResponse(Object(Buzz\Message\Response))
#3 /home/iqdoctor/Hr360Bot/vendor/toin0u/digitalocean-v2/src/Api/Droplet.php(179): DigitalOceanV2\Adapter\BuzzAdapter->delete('https://api.dig...')
#4 /home/iqdoctor/Hr360Bot/app/do2.2.php(854): DigitalOceanV2\Api\Droplet->delete(109473727)
#5 /home/iqdoctor/Hr360Bot/app/do2.2.php(259): deleteDroplete in /home/iqdoctor/Hr360Bot/vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php on line 148

**Comment by iqdoctor** [comment]
i think if $body is not valid json, for exsample in case 500 Internal server error, code in \DigitalOceanV2\Adapter\BuzzAdapter::handleError works wrong.

**Comment by glennjacobs** [comment]
This is very old. I'm going to close as the error doesn't match the current version of the package.
