### ISSUE TITLE
Feature request: API for Spaces

### ISSUE THREAD

**Issue by vousys** [DigitalOceanPHP/DigitalOceanV2#202]
Hi Guys, Are you planning to add functions to handle spaces?
https://developers.digitalocean.com/documentation/spaces/#object-ops

**Comment by kovkor** [comment]
+1 for this, thank you!

**Comment by tspencer244** [comment]
Shouldn't this be a separate library since it's a separate API?

**Comment by Conver** [comment]
+1

**Comment by glennjacobs** [comment]
It's a separate API, but it's certainly something to be considered.

Here's a link to the documentation.
https://developers.digitalocean.com/documentation/spaces/

Any suggestions on how we should support this?

**Comment by GrahamCampbell** [comment]
We don't be supporting the spaces API here (apart from possibly a small number of meta methods) because their API was designed to be S3-compatible, so you can just use Amazon's SDK (https://github.com/aws/aws-sdk-php) or alternative S3 clients such as https://github.com/async-aws/aws.

**Comment by wrabit** [comment]
@GrahamCampbell Apart from Spaces CDN
