### ISSUE TITLE
Repo Maintenace

### ISSUE THREAD

**Issue by cballou** [DigitalOceanPHP/DigitalOceanV2#204]
Someone willing to maintain should fork this repo and add it to packagist. It's clear @toin0u is busy and no longer able to keep up with pull requests and versioning.

**Comment by GrahamCampbell** [comment]
@toin0u should be able to add more collaborators to this repo, like myself. Unfortunately I don't have permission, since this repo doesn't belong to an organization.

**Comment by yassirh** [comment]
Hello @cballou I will try to merge all the pull requests soon.

**Comment by browner12** [comment]
Agreed, last release was 18 months ago.

Maybe add an extra collaborator or 2 so we can get some more progress on this repo.

**Comment by GrahamCampbell** [comment]
If I could add collaborators, I would.

**Comment by GrahamCampbell** [comment]
Only @toin0u can.

**Comment by GrahamCampbell** [comment]
> Maybe add an extra collaborator or 2 so we can get some more progress on this repo.

There are no waiting changes though? If people PR stuff, it'll be merged.

**Comment by browner12** [comment]
thanks, appreciate it.

**Comment by GrahamCampbell** [comment]
See https://github.com/toin0u/DigitalOceanV2/issues/237. I have now left as a maintainer of this repo.
