### ISSUE TITLE
Cannot log into droplets after creating them programatically

### ISSUE THREAD

**Issue by AndreFabris** [DigitalOceanPHP/DigitalOceanV2#224]
Hello,

this all works fine for me (I am using Graham's Laravel wrapper), so I can create SSH key pairs, create a droplet and set it all up. Droplets work fine, all is great. 

To generate key pair for each droplet I am using this:
https://github.com/ssx/php-ssh-keypair/blob/master/src/KeyPair.php

Now the problem is when I try to access droplet via Putty or similar using Private key I cannot as it has not been saved in PPT/PEM format. I just have a text that is generated such as:

-----BEGIN RSA PRIVATE KEY----- MIIJKQIB ................ -----END RSA PRIVATE KEY-----

I know this is not the library issue, but it is related, and I hope that someone from community can point me in the right direction as I cannot find relevant solutions online.

Many thanks!

**Comment by glennjacobs** [comment]
Do you still need help with this?
