### ISSUE TITLE
How to capture Timeout Error from Buzz\Exception\RequestException

### ISSUE THREAD

**Issue by ggedde** [DigitalOceanPHP/DigitalOceanV2#230]
I cannot figure out how to Capture the RequestException when there is a timeout error.
As a result I get a Fatal Error:
`Fatal error: Uncaught Buzz\Exception\RequestException: Operation timed out after`

Instead I have tried to capture it, but it does not work.

I have tried all the following:

```
$droplet = $digitalocean->droplet();

try 
{
	$rebooted = $droplet->reboot('123456789');
}
catch (RequestException | HttpException | Exception $e) 
{
	$error_message = $e->getMessage();
}
```

```
$droplet = $digitalocean->droplet();

try 
{
	$rebooted = $droplet->reboot('123456789');
}
catch (RequestException $e) 
{
	$error_message = $e->getMessage();
}
```

```
$droplet = $digitalocean->droplet();

try 
{
	$rebooted = $droplet->reboot('123456789');
}
catch (\Buzz\Exception\RequestException $e) 
{
	$error_message = $e->getMessage();
}
```

I have also tried adding at the top:
use Buzz\Exception\RequestException
or 
use Buzz\Exception

But I am still not able to capture the error.

Any help would be appreciated.

Thanks

**Comment by GrahamCampbell** [comment]
~Moving to part of the v4 design issue #249. I am planning to smash out a fresh package for v4 which will feel like the old package, but have none of the issues and all of the compatibility. ;)~ EDIT: See comment below.

**Comment by GrahamCampbell** [comment]
Update: Actually, I will address this in time for the 3.0.0 release.
