### ISSUE TITLE
Feature request: API for Firewalls

### ISSUE THREAD

**Issue by Conver** [DigitalOceanPHP/DigitalOceanV2#232]
Hello,

I've been looking thru the code and it doesn't seem there is a way to control firewalls?

It would be a very neat function, being able to block an IP from accessing your server on network level completely.

**Comment by Conver** [comment]
Just found out that it isn't possible, but I've added an idea post to DO to see if they'll add it.

https://ideas.digitalocean.com/ideas/FWX-I-11 <- Please give your vote!

**Comment by glennjacobs** [comment]
The firewall API would be very handy. I'd consider adding this feature if it was likely to be considered. Is this repo being actively maintained?

**Comment by glennjacobs** [comment]
Looks like you can add rules now, see https://developers.digitalocean.com/documentation/v2/#add-rules-to-a-firewall

I'm going to need firewall control soon, so will be working on it.

**Comment by GrahamCampbell** [comment]
Moving to part of the v4 design issue #249. I am planning to smash out a fresh package for v4 which will feel like the old package, but have none of the issues and all of the compatibility. ;)
