### ISSUE TITLE
Updating an image from the git repository for droplets

### ISSUE THREAD

**Issue by lusy777** [DigitalOceanPHP/DigitalOceanV2#239]
I have an existing image on which the droplet is built. I use this library and I need to update the current image through git using api. Tell me how to do it please (if this possible off course)

**Comment by glennjacobs** [comment]
If you take a look at https://developers.digitalocean.com/documentation/v2/#images you'll see what options there are.

I don't think this package currently supports what you require, but you're welcome to do a pull request to add it in.

**Comment by GrahamCampbell** [comment]
~Moving to part of the v4 design issue #249. I am planning to smash out a fresh package for v4 which will feel like the old package, but have none of the issues and all of the compatibility. ;)~

**Comment by GrahamCampbell** [comment]
It is not possible to "upload" images using their API.
