### ISSUE TITLE
Buzz 1.x support

### ISSUE THREAD

**Issue by glennjacobs** [DigitalOceanPHP/DigitalOceanV2#245]
Update Buzz to latest version

https://github.com/kriswallsmith/Buzz

**Comment by GrahamCampbell** [comment]
Moving to part of the v4 design issue https://github.com/DigitalOceanPHP/DigitalOceanV2/issues/249. I am planning to smash out a fresh package for v4 which will feel like the old package, but have none of the issues and all of the compatibility. ;)
