### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by glennjacobs** [DigitalOceanPHP/DigitalOceanV2#247]
We have some pull requests in the waiting, do we want to get them merged into a 2.4 release?

Or shall we wait for some more substantial improvements?

**Comment by cam-vanorman** [comment]
Hey @glennjacobs, I haven't had a chance to get back to this repo and follow-up with the open pull requests. I can set time aside in the next couple of weeks to test/review a few PRs. Let me know if there are any you want to test/review and I can assign myself to a few others for review.

**Comment by GrahamCampbell** [comment]
There is currently no 2.4.x release series. We only have 2.3.x on the 2.3 branch and 3.0.x on the master branch.

**Comment by GrahamCampbell** [comment]
There have already been breaking changes on the master branch, like removing guzzle 3 support, and also (technically not breaking) the removal of support for PHP 5 and 7.0.

**Comment by GrahamCampbell** [comment]
https://github.com/DigitalOceanPHP/DigitalOceanV2/compare/2.3.0...master

**Comment by GrahamCampbell** [comment]
The next release will be 3.0.0 I guess (there are no untagged changes on the 2.3 branch at the moment).
