### ISSUE TITLE
Implement links information about the response

### ISSUE THREAD

**Issue by toin0u** [DigitalOceanPHP/DigitalOceanV2#7]
More info [here](https://developers.digitalocean.com/#links)

**Comment by Teevio** [comment]
Updated link for relevant docs: https://developers.digitalocean.com/documentation/v2/#links

**Comment by GrahamCampbell** [comment]
Moving to part of the v4 design issue https://github.com/DigitalOceanPHP/DigitalOceanV2/issues/249. I am planning to smash out a fresh package for v4 which will feel like the old package, but have none of the issues and all of the compatibility. ;)

**Comment by GrahamCampbell** [comment]
EDIT: Pagination is now implemented in v3.0.0 without using links. Once we remove entities in v4, we'll be able to re-implement pagination using links, properly.
